/* Logico_sisMusica: */

CREATE TABLE ESTILO (
    Id_estilo NUMERIC(5) PRIMARY KEY,
    estilo VARCHAR(50)
);

CREATE TABLE ARTISTA (
    id_artista NUMERIC(5) PRIMARY KEY,
    nome VARCHAR(30),
    bibliografia VARCHAR(500),
    FK_PAIS_id_pais NUMERIC(5)
);

CREATE TABLE ALBUM (
    id_album NUMERIC(5) PRIMARY KEY,
    titulo VARCHAR(30),
    ano_lancamento NUMERIC(4),
    img_capa BLOB,
    gravadora VARCHAR(30)
);

CREATE TABLE PAIS (
    id_pais NUMERIC(5) PRIMARY KEY,
    nome_pais VARCHAR(30),
    sigla VARCHAR(3)
);

CREATE TABLE MUSICA (
    ordemMUSICA NUMERIC(3),
    idMUSICA NUMERIC(5) PRIMARY KEY,
    titulo VARCHAR(30),
    duracao NUMERIC(5),
    ano NUMERIC(4),
    letra CLOB,
    arquivo BLOB,
    tags VARCHAR(20),
    FK_ESTILO_Id_estilo NUMERIC(5),
    FK_ARTISTA_id_artista NUMERIC(5),
    FK_ALBUM_id_album NUMERIC(5)
);

CREATE TABLE USUARIO (
    id_usuario NUMERIC(5) PRIMARY KEY,
    email VARCHAR(30),
    senha VARCHAR(30),
    nome VARCHAR(30),
    foto BLOB,
    FK_PLANO_id_plano NUMERIC(5)
);

CREATE TABLE PLANO (
    id_plano NUMERIC() PRIMARY KEY,
    titulo VARCHAR(30),
    descricao VARCHAR(100),
    valor NUMERIC(5),
    vigencia NUMERIC(5)
);

CREATE TABLE COBRANCA (
    id_cobranca NUMERIC(5) PRIMARY KEY,
    data_pagto NUMERIC(8),
    valor NUMERIC(5),
    final_cartao NUMERIC(4),
    FK_PLANO_id_plano NUMERIC(5),
    FK_USUARIO_id_usuario NUMERIC(5)
);

CREATE TABLE CARTAO_CREDITO (
    id_cartao NUMERIC(5) PRIMARY KEY,
    nome_impressao VARCHAR(30),
    validade NUMERIC(6),
    numero NUMERIC(16),
    cvv NUMERIC(3),
    FK_USUARIO_id_usuario NUMERIC(5)
);

CREATE TABLE LISTA_REPROD (
    id_lista NUMERIC(5) PRIMARY KEY,
    nome VARCHAR(30),
    FK_USUARIO_id_usuario NUMERIC(5)
);

CREATE TABLE MUSICA_LISTA_REPROD (
    ordemMUSICA NUMERIC,
    FKMUSICA_idMUSICA NUMERIC,
    FK_LISTA_REPROD_id_lista NUMERIC
);

CREATE TABLE Dependentes (
    fk_USUARIO_id_usuario NUMERIC,
    fk_USUARIO_id_usuario_ NUMERIC
);
 
ALTER TABLE ARTISTA ADD CONSTRAINT FK_ARTISTA_2
    FOREIGN KEY (FK_PAIS_id_pais)
    REFERENCES PAIS (id_pais)
    ON DELETE CASCADE;
 
ALTER TABLE MUSICA ADD CONSTRAINT FK_MUSICA_2
    FOREIGN KEY (FK_ESTILO_Id_estilo)
    REFERENCES ESTILO (Id_estilo);
 
ALTER TABLE MUSICA ADD CONSTRAINT FK_MUSICA_3
    FOREIGN KEY (FK_ARTISTA_id_artista)
    REFERENCES ARTISTA (id_artista);
 
ALTER TABLE MUSICA ADD CONSTRAINT FK_MUSICA_4
    FOREIGN KEY (FK_ALBUM_id_album)
    REFERENCES ALBUM (id_album);
 
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_2
    FOREIGN KEY (FK_PLANO_id_plano)
    REFERENCES PLANO (id_plano)
    ON DELETE CASCADE;
 
ALTER TABLE COBRANCA ADD CONSTRAINT FK_COBRANCA_2
    FOREIGN KEY (FK_PLANO_id_plano)
    REFERENCES PLANO (id_plano)
    ON DELETE CASCADE;
 
ALTER TABLE COBRANCA ADD CONSTRAINT FK_COBRANCA_3
    FOREIGN KEY (FK_USUARIO_id_usuario)
    REFERENCES USUARIO (id_usuario)
    ON DELETE CASCADE;
 
ALTER TABLE CARTAO_CREDITO ADD CONSTRAINT FK_CARTAO_CREDITO_2
    FOREIGN KEY (FK_USUARIO_id_usuario)
    REFERENCES USUARIO (id_usuario)
    ON DELETE CASCADE;
 
ALTER TABLE LISTA_REPROD ADD CONSTRAINT FK_LISTA_REPROD_2
    FOREIGN KEY (FK_USUARIO_id_usuario)
    REFERENCES USUARIO (id_usuario)
    ON DELETE CASCADE;
 
ALTER TABLE MUSICA_LISTA_REPROD ADD CONSTRAINT FK_MUSICA_LISTA_REPROD_1
    FOREIGN KEY (FKMUSICA_idMUSICA)
    REFERENCES ??? (???);
 
ALTER TABLE MUSICA_LISTA_REPROD ADD CONSTRAINT FK_MUSICA_LISTA_REPROD_2
    FOREIGN KEY (FK_LISTA_REPROD_id_lista)
    REFERENCES LISTA_REPROD (id_lista);
 
ALTER TABLE Dependentes ADD CONSTRAINT FK_Dependentes_1
    FOREIGN KEY (fk_USUARIO_id_usuario)
    REFERENCES USUARIO (id_usuario)
    ON DELETE CASCADE;
 
ALTER TABLE Dependentes ADD CONSTRAINT FK_Dependentes_2
    FOREIGN KEY (fk_USUARIO_id_usuario_)
    REFERENCES USUARIO (id_usuario)
    ON DELETE CASCADE;